### ISSUE TITLE
At what time is the SMS sent?

### ISSUE THREAD

**Issue by IonicaBizau** [BibleJS/bibletext.co#17]
I setup my phone number and I'm waiting for the SMS. :smile:

**Comment by IonicaBizau** [comment]
Hmm... I didn't get any messages on my phone yet. Is the service supported in all countries?

**Comment by fpereira1** [comment]
The message is sent everyday at 7.30 am NZT - I will add that `/send` route we talked about ;)

**Comment by IonicaBizau** [comment]
@fpereira1 But the issue is that I didn't get any messages yet. Is possible that the support is related some specific countries?

**Comment by IonicaBizau** [comment]
@fpereira1 *Here's a test*, received it! :smile:

**Comment by fpereira1** [comment]
@IonicaBizau  yes, you're right - I needed to enable your country to the geographic restrictions in the twilio admin panel.  I enabled it now. :+1:

**Comment by IonicaBizau** [comment]
Wow, cool! Thanks! :+1:

**Comment by fpereira1** [comment]
Cool, let me know if you receive a message in the next couple of days.

**Comment by IonicaBizau** [comment]
Sure, I will! :smile:
