### ISSUE TITLE
Remove HTML tags

### ISSUE THREAD

**Issue by IonicaBizau** [BibleJS/bibletext.co#19]
![image](https://cloud.githubusercontent.com/assets/2864371/5337361/1d0e73c2-7ed0-11e4-9d89-b2b3d7316168.png)

http://stackoverflow.com/a/5002161/1420197

**Comment by fpereira1** [comment]
that was addressed in bible.js https://github.com/BibleJS/bible.js/issues/6 - will update the dependency
